### ISSUE TITLE
Place bet function 

### ISSUE THREAD

**Issue by abyll** [ProjectRevoTPP/musiccat#3]
place_bet(username, amount, songid, category) - passed from the parse_bid function

Verify the song is valid for the category
Check the new bid against any existing bid for that category
Record the new bid (if won), and make the quantity of bet tokens available back to the Tokens module.

**Comment by RevoSucks** [comment]
This should be handled by bidCat instead and whatever raised the bet in the first place. Instead, musicCat is called to play the winning song.
